### ISSUE TITLE
Pause on Android

### ISSUE THREAD

**Issue by julianCast** [wizpanda/cordova-plugin-nativeaudio#3]
Hi! Awesome fork but one question: Is it possible to pause the audio?
I can see references to it the Java files. 

Thank you!

**Comment by sagrawal31** [comment]
Hi, apologies for the late reply. I was on paternal leave. I can try looking for Android, but for iOS, I have limited knowledge. I did a search for you and I was surprised to see that there is an existing official plugin for media https://github.com/apache/cordova-plugin-media. Give it a try, please.

**Comment by julianCast** [comment]
Congrats for the baby! I end it up just using regular HTML5 audio, perfect for my purpose.

For those we want a pause on this plugin, a simple dummy workaround is modifying the stop function to make it work like a pause, just removing the line that set the seek to 0 in the javascript files.

**Comment by sagrawal31** [comment]
Thanks, @julianCast for the warm wishes!

Got your workaround about removing the line.
